//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeminarioLP3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loja
    {
        public int IdLoja { get; set; }
        public int FkRua { get; set; }
        public string NomeComercial { get; set; }
        public string CNPJ { get; set; }
        public string RazaoSocial { get; set; }
        public string Telefone { get; set; }
        public string Site { get; set; }
    
        public virtual Rua Rua { get; set; }
    }
}
