//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeminarioLP3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeminarioLP3Container : DbContext
    {
        public SeminarioLP3Container()
            : base("name=SeminarioLP3Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rua> Rua { get; set; }
        public virtual DbSet<TipoComercio> TipoComercio { get; set; }
        public virtual DbSet<Bairro> Bairro { get; set; }
        public virtual DbSet<CategoriaProduto> CategoriaProdutoSet { get; set; }
        public virtual DbSet<Loja> Loja { get; set; }
    }
}
