//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeminarioLP3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoComercio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoComercio()
        {
            this.Rua = new HashSet<Rua>();
            this.CategoriaProduto = new HashSet<CategoriaProduto>();
        }
    
        public int IdComercio { get; set; }
        public string Nome { get; set; }
        public string OrgaoRegulador { get; set; }
        public string Permissao { get; set; }
        public string Descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rua> Rua { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriaProduto> CategoriaProduto { get; set; }
    }
}
